service: test-lamda-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello/get
          method: get
plugins:
  - serverless-offline
